name: grow
recipe: laravel
config:
  webroot: public
  via: nginx
  php: '8.1'
  composer:
    'deployer/deployer' : 'v7.0.0-rc.9'
services:
  appserver:
    overrides:
      environment:
        - SSH_AUTH_SOCK=/ssh-agent
      volumes:
        - ${SSH_AUTH_SOCK}:/ssh-agent
  database:
    creds:
      user: grow
      password: grow
      database: grow
  node:
    type: node:14
    build:
      - npm install
    scanner: false
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts: database
tooling:
  node:
    service: node
  npm:
    service: node
  dep:
    service: appserver
    description: Run deployer commands
    cmd:
      - "dep"
  refresh:
    service: appserver
    description: Refresh project with new DB
    cmd:
      - "php artisan db:wipe"
      - "php artisan migrate"
      - "php artisan db:seed"
proxy:
  node:
    - bs.grow.lndo.site:3000
  pma:
    - pma.grow.lndo.site
